/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import useTamagotchiStore from "../../stores/useTamagotchiStore";

type GLTFResult = GLTF & {
  nodes: {
    Plate_2: THREE.Mesh;
  };
  materials: {
    ["White.002"]: THREE.MeshStandardMaterial;
  };
};

export default function Plate(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/furniture/Plate.glb"
  ) as GLTFResult;
  const currentFood = useTamagotchiStore((state) => state.currentFood);

  return (
    <group {...props} dispose={null}>
      <group position-y={-0.04}>{currentFood && <currentFood.Model />}</group>

      <group scale={[2.3, 1, 2.3]}>
        <mesh
          castShadow
          geometry={nodes.Plate_2.geometry}
          material={materials["White.002"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/furniture/Plate.glb");
